### ISSUE TITLE
Add workflows to katib-rocks repository

### ISSUE THREAD

**Issue by i-chvets** [canonical/katib-rocks#30]
# Description

Workflows are needed to ensure proper validation of changes to ROCK images.

Add workflows to https://github.com/canonical/katib-rocks
- on pull request execute ROCKs unit tests
- on pull requests execute ROCKs integration tests ?????
- publish workflow

Verify build and scan workflow works for all ROCKs (disk space issue is resolved)

**Comment by orfeas-k** [comment]
Closing in favor of https://github.com/canonical/katib-rocks/issues/42
