### ISSUE TITLE
`katib-ui-rock` is based on wrong Dockerfile

### ISSUE THREAD

**Issue by orfeas-k** [canonical/katib-rocks#32]
It turns out we have ROCKed the wrong dockerfile for `katib-ui-rock`.

The katib-ui component we 've charmed is the until recently (release `0.15`) called `new-ui` component in the upstream. We can see this in the way they [produced images](https://github.com/kubeflow/katib/blob/v0.15.0/.github/workflows/publish-core-images.yaml#L27-L28). Looking at the`0.15` release branch, this is the [dockerfile](https://github.com/kubeflow/katib/blob/v0.15.0/cmd/ui/v1beta1/Dockerfile) we rocked while the image we use in our charm comes from [this one](https://github.com/kubeflow/katib/blob/v0.15.0/cmd/new-ui/v1beta1/Dockerfile). With release `0.16`, [they removed the old ui](https://github.com/kubeflow/katib/pull/2179) and thus renamed previous `new-ui` component to `ui`. 

Summarizing, we need to update the ROCK to be based on [this dockerfile](https://github.com/kubeflow/katib/blob/v0.16.0-rc.1/cmd/ui/v1beta1/Dockerfile) (`ui` from release `0.16-rc.1`).

**Comment by ca-scribner** [comment]
This will be closed by https://github.com/canonical/katib-rocks/issues/32
